list:
  path: /
  methods: [GET]
  controller: App\ScreamingFrog\Controller\CrawlController::list

group:
  path: /group/{group}/{page}
  methods: [GET]
  controller: App\ScreamingFrog\Controller\CrawlController::group

show:
  path: /group/{group}/crawl/{crawl}
  methods: [GET, POST]
  controller: App\ScreamingFrog\Controller\CrawlController::show

new:
  path: /new
  methods: [GET, POST]
  controller: App\ScreamingFrog\Controller\CrawlController::new