list:
  path: /list/{group}/{page}
  methods: [GET]
  controller: App\Controller\CrawlController::list

show:
  path: /show/{group}/{crawl}
  methods: [GET, POST]
  controller: App\Controller\CrawlController::show